server:
  port: ${port:50000}
  servlet:
    contextPath: "/brcode"

spring:
  main:
    banner-mode: "off"
  application:
    name: "urd"

logging:
  group:
    brcode: com.br.valhalla.brcodegeneration, com.br.valhalla.brcodegeneration.service, com.br.valhalla.brcodegeneration.controller
  path: "logs"
  file: "${logging.path}/${spring.application.name}.log"
  pattern:
    console: "# ${spring.application.name} | %d{dd-MM-yyyy HH:mm:ss.SSS} | %-5level |  %thread  | %logger{0} | %msg%n"
    file: "# ${spring.application.name} | %d{dd-MM-yyyy HH:mm:ss.SSS} | %-5level |  %thread  | %logger{0} | %msg%n"
  level:
    root: info
    brcode: info